version: '3.7'
services:
  app:
    image: jetpackpony/pubg-quickstats-api
    container_name: pubg-quickstats-api
    restart: always
    networks:
      - web
      - default
    expose:
      - 4000
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.port=4000"
      - "traefik.protocol=http"
    env_file:
      - .env
    command: npm run start:prod

networks:
  web:
    external: true
